version: '3.8'

services:
  react-build:
    build:
      context: ./portfolio
      dockerfile: Dockerfile
    # Map the build output from the container to the local ./build folder.
    volumes:
      - ./build:/app/build
    # Optionally, you can override the command if you want to be explicit.
    command: ["npm", "run", "build"]
