version: '3.9'  # Use version 3.9 or higher

services:
  portfolio:
    container_name: portfolio-nextjs
    build:
      context: ./portfolio  # This is the directory where the Dockerfile is located
      dockerfile: Dockerfile  # Optional if Dockerfile is named `Dockerfile`
    platform: linux/amd64  # Specify x86_64 architecture here
    image: personal-website:arm64   # Tag your image as 'myimage:arm64'
    
    ports:
      - "3000:3000"
    
    volumes:
      - ./portfolio:/app    # Mounts project directory to container
      - /app/node_modules   # Prevents conflicts between host & container dependencies
