name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different.

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository.
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Build the React app using Docker Compose.
      - name: Build React App with Docker Compose
        run: docker-compose up --build

      # 3. Deploy to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
